name = "gar-utas-app"
compatibility_date = "2024-04-15"
pages_build_output_dir = "dist"

# Enable Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "gar-utas-d1"
database_id = "00000000-0000-0000-0000-000000000000"

# Enable Cloudflare R2
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "gar-utas-images"
